plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
markdown: kramdown

theme: minima

syntax_highlighter_opts:
  disable: true

collections:
  about:
    output: true
  doc:
    output: true
  tutorial:
    output: true
  FAQ:
    output: true
  examples:
    output: true
  external:
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
      author: OSGiAlliance
      image: /img/enroute-logo-64.png

title: OSGi enRoute

logo: /img/enroute-logo-64.png

twitter:
  username: OSGiAlliance

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'README.md'
  - 'CONTRIBUTING.md'
  - 'LICENSE'
  - 'run.sh'
  - '.travis.yml'
  - '.gitignore'
  - '.gitmodules'
  - 'run.sh'
  - '/vendor'
